# stacks node config
[node]
# where the node stores stacks chain data
working_dir = "/root/stacks-node/data"
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
# the nodes used to bootstrap your node
# these are hiro's nodes, but you can use any other nodes too
bootstrap_node = "02da7a464ac770ae8337a343670778b93410f2f3fef6bea98dd1c3e9224459d36b@seed-0.mainnet.stacks.co:20444,02afeae522aab5f8c99a00ddf75fbcb4a641e052dd48836408d9cf437344b63516@seed-1.mainnet.stacks.co:20444,03652212ea76be0ed4cd83a25c06e57819993029a7b9999f7d63c36340b34a4e62@seed-2.mainnet.stacks.co:20444"

# time in ms to wait for a microblock
wait_time_for_microblocks = 10000

[[events_observer]]
endpoint = "stacks-blockchain-api:3700"
retry_count = 255
events_keys = ["*"]

[burnchain]
chain = "bitcoin"
mode = "mainnet"

# YOU SHOULD BE RUNNING YOUR OWN BITCOIN CORE NODE
# https://docs.syvita.org/understand-stacks/running-mainnet-node#step-2-running-bitcoin-core

# this is halo's bitcoin core node
# change to "localhost" if Bitcoin Core is running on the same system
peer_host = "94.237.60.208"
username = ""
password = ""
rpc_port = 8332
peer_port = 8333